version: '3'
services:

  # The Application
  laravel-app:
    volumes:
      - ./public:/var/www/
    working_dir: /var/www/
    build:
      args:
        user:  ${USER}
        uid: 1000
      context: ./
      dockerfile: app.dockerfile
    command: php-fpm
    networks:
        - my-network
  # The Web Server nginx
  laravel-web:
    build:
      context: ./
      dockerfile: web.dockerfile
      args:
        user:  ${USER}
        uid: 1000
    depends_on:
      - laravel-app
    working_dir: /var/www
    volumes:
      - ./public:/var/www/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my-network
    ports:
      - "9091:80"
networks:
  my-network:
    driver: bridge
