version: '3'
services:

  # The Application
  app:
    volumes:
      - ./public/:/var/www
    working_dir: /var/www
    build:
      args:
        user:  ${USER}
        uid: 1000
      context: ./
      dockerfile: app.dockerfile
    environment:
      DB_PORT: 3306
      DB_HOST: database
    command: php-fpm
    networks:
        - my-network
  # The Web Server nginx
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - ./public/:/var/www
    networks:
      - my-network
    ports:
      - 8080:80

  # The Database
  database:
    image: mariadb:10.5.1
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/init:/docker-entrypoint-initdb.d
    environment:
      TZ: "America/La_Paz"
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_USER: homestead
      MYSQL_PASSWORD: homestead
      MYSQL_DATABASE: homestead
    networks:
      - my-network
    ports:
        - "3306:3306"

  phpmyadmin:
    image:  phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    networks:
      - my-network
    ports:
      - "8081:80"

volumes:
  dbdata:

networks:
  my-network:
    driver: bridge